### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by EthanZeigler** [TomerADev/mano-simulator#3]
What's an IDE without syntax highlighting? Lol.

Assigning myself to implement syntax highlighting using SyntaxTextAreaFX.

**Comment by TomerAberbach** [comment]
Thanks for working on this! Feel free to make a pull request whenever you're done.

Also, I didn't get any email or notification from GitHub about this issue for some reason. Any idea how to fix that? Do I have to be watching my own repository?

**Comment by EthanZeigler** [comment]
Notifications are broken across all platforms. It’s been a time.

**Comment by TomerAberbach** [comment]
So does that mean that watching my own repository won't fix the issue?

**Comment by EthanZeigler** [comment]
No guarantee, no. Fun, right? Same thing happens when you add contributors. No notification to the user.

**Comment by TomerAberbach** [comment]
Well I guess I'll watch the repository and hope.
