### ISSUE TITLE
Mano Simulator not installing

### ISSUE THREAD

**Issue by d-parikh** [TomerADev/mano-simulator#4]
I have downloaded the mano simulator but it is not opening....Kindly look for the solution

**Comment by TomerAberbach** [comment]
I'll need more information than you've provided to diagnose the problem. Run the JAR in the terminal via `java -jar filename` (with `filename` replaced by the name of the JAR file you downloaded) and paste any errors you get here

**Comment by d-parikh** [comment]
C:\Users\Bharat\Downloads>java -jar mano-simulator.jar
Error: Could not find or load main class
com.tomeraberbach.mano.application.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

C:\Users\Bharat\Downloads>java -jar mano-simulator
Error: Unable to access jarfile mano-simulator

**Comment by d-parikh** [comment]
Do we  have to add any path for mano????

**Comment by TomerAberbach** [comment]
The first command you ran was correct. The error indicates that you don't have JavaFX installed. You need to install it

**Comment by TomerAberbach** [comment]
Some Java installations bundle JavaFX, but not all so you must have installed one that doesn't

**Comment by d-parikh** [comment]
My mano simulator started....Thanks a lot for guiding

**Comment by TomerAberbach** [comment]
No problem! I'm glad I could help and I'm glad that you shared your issue. I'll amend the README to indicate that JavaFX must be installed in order for the application to work
