### ISSUE TITLE
Want to contribute in this Simulator

### ISSUE THREAD

**Issue by prashant0ngx** [TomerADev/mano-simulator#7]
Hello ,I am student and currently studying Bachelor of Information Management at Tribhuvan University. As I have the "Computer Organization" Subject in 3rd semester.

Text book: - M. Morris Mano, Computer System Architecture 3rd Edition

I found that the simulator only show the outputs value in Hex and I found it annoying every time. So  I decided to work on your simulator
I clone the project and did the some changes. 
Successfully, I made the project what i was seeking a lot. The simulator now show the outputs in different tabs: Hexa-Decimal, Decimal, Binary.

And experimented all the  programs listed in Text Book. Its working fine.
Please reference from here:

https://github.com/TECHPRASANT/co-simulator

If you want to merge that code .. please reply...

**Comment by TomerAberbach** [comment]
It's not really feasible to review your code in its current state. If you'd like to contribute, then please open a pull request instead
